### ISSUE TITLE
Question about bijective graphs isomorphism

### ISSUE THREAD

**Issue by wojdyr** [GiugnoLab/RI#2]
Hi, thanks for making your code available.
I don't know much about graph algorithms, so it may be a naive question.

I'm looking for a C++ library that would allow me to iterate over all automorphisms of a graph. (background: I want to superpose two 3D models of small molecules. The graphs of a molecule can have symmetries, so I can't be sure which atoms in the two molecules correspond to each other. Therefore, I want to try all automorphisms of one of the molecules)

I read that this library can find graph isomorphisms. Am I right that it can be used to find automorphisms?
Your 2013 paper compares performance of the *sub*graph isomorphism algorithms. Do you know how the performance of graph isomorphism in RI compares to other algorithms/libraries such as nauty, saucy or bliss?

**Comment by vbonnici** [comment]
Dear Marcin
RI is mainly developed for subgraph isomorphism, that is monomorphism and
induced subgraph isomorphism,
thus it is likely that ad hoc solutions for graph isomorphism and
automorphism exist and that they are faster than RI in solving these
problems.
 I hope this email was helpful to you
Best wishes
Vincenzo

**Comment by wojdyr** [comment]
Thanks for quick reply!
